version: '3.1'

services:
  writer-webapp:
   build:
     context: .
     dockerfile: Dockerfile
   ports:
     - "8080:8080"
  db:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
volumes:
  my-db: